[providers]
java = "17"

[variables]
SPRING_PROFILES_ACTIVE = "railway"
PORT = "8080"
JAVA_OPTS = "-Xmx512m -Xms256m -XX:+UseG1GC"

# URLs de servicios internos (Railway)
USERS_SERVICE_URL = "https://users-service.railway.internal"
AUTH_SERVICE_URL = "https://auth-service.railway.internal"
PROD_SERVICE_URL = "https://prod-service.railway.internal"
FILE_SERVICE_URL = "https://file-service.railway.internal"
ORDER_SERVICE_URL = "https://order-service-deploy.railway.internal"
STATS_SERVICE_URL = "https://stats-service.railway.internal"

# Configuración de métricas
MANAGEMENT_METRICS_ENABLE_SYSTEM = "false"
MANAGEMENT_METRICS_ENABLE_PROCESS = "false"
MANAGEMENT_METRICS_ENABLE_JVM = "true"

[build]
cmd = "mvn clean package -DskipTests"

[start]
cmd = "java $JAVA_OPTS -jar target/*.jar"