# src/main/resources/application-railway.yml
# Asegúrate de que el perfil está activo en Railway (variable SPRING_PROFILES_ACTIVE=railway)
spring:
  config:
    activate:
      on-profile: railway

  cloud:
    gateway:
      routes:
        - id: users-service
          uri: lb://users-service
          predicates:
            - Path=/api/users/**
          filters:
            - StripPrefix=1
            # Ya no necesitas DedupeResponseHeader aquí ni en default-filters,
            # tu CorsWebFilter global se encarga de los headers CORS.

        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/api/auth/**
          filters:
            - StripPrefix=1

        - id: prod-service
          uri: lb://prod-service
          predicates:
            - Path=/api/products/**
          filters:
            - StripPrefix=1

        - id: file-service
          uri: lb://file-service
          predicates:
            - Path=/api/files/**
          filters:
            - StripPrefix=1

        - id: order-service
          uri: lb://order-service-deploy # Asegúrate de que este es el nombre EXACTO de Railway
          predicates:
            - Path=/api/orders/**
          filters:
            - StripPrefix=1

        - id: stats-service
          uri: lb://stats-service
          predicates:
            - Path=/api/stats/**
          filters:
            - StripPrefix=1

        - id: health
          uri: http://localhost:8080/actuator/health
          predicates:
            - Path=/health

    loadbalancer:
      ribbon:
        enabled: false # Esto asegura que no intente usar el cliente Ribbon obsoleto
      clients:
        users-service:
          ribbon:
            listOfServers: ${USERS_SERVICE_URL}:8080
        auth-service:
          ribbon:
            listOfServers: ${AUTH_SERVICE_URL}:8080
        prod-service:
          ribbon:
            listOfServers: ${PROD_SERVICE_URL}:8080
        file-service:
          ribbon:
            listOfServers: ${FILE_SERVICE_URL}:8080
        order-service-deploy:
          ribbon:
            listOfServers: ${ORDER_SERVICE_URL}:8080
        stats-service:
          ribbon:
            listOfServers: ${STATS_SERVICE_URL}:8080