# src/main/resources/application-railway.yml
spring:
  config:
    activate:
      on-profile: railway

  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin

      routes:
        - id: users-service
          uri: http://${USERS_SERVICE_URL}:${PORT}      # 87e0f0….railway.internal
          predicates:
            - Path=/api/users/**
          filters:
            - StripPrefix=1

        - id: auth-service
          uri: http://${AUTH_SERVICE_URL}:${PORT}
          predicates:
            - Path=/api/auth/**
          filters:
            - StripPrefix=1

        - id: prod-service
          uri: http://${PROD_SERVICE_URL}:${PORT}
          predicates:
            - Path=/api/products/**
          filters:
            - StripPrefix=1

        - id: file-service
          uri: http://${FILE_SERVICE_URL}:${PORT}
          predicates:
            - Path=/api/files/**
          filters:
            - StripPrefix=1

        - id: order-service
          uri: http://${ORDER_SERVICE_URL}:${PORT}
          predicates:
            - Path=/api/orders/**
          filters:
            - StripPrefix=1

        - id: stats-service
          uri: http://${STATS_SERVICE_URL}:${PORT}
          predicates:
            - Path=/api/stats/**
          filters:
            - StripPrefix=1

        # Health del propio gateway
        - id: health
          uri: http://localhost:${PORT}/actuator/health
          predicates:
            - Path=/health

      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOriginPatterns: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
            allowCredentials: true
            maxAge: 3600

server:
  port: ${PORT:8080}

logging:
  level:
    org.springframework.cloud.gateway: INFO
    root: INFO
