# src/main/resources/application-railway.yml

spring:
  config:
    activate:
      on-profile: railway

  cloud:
    gateway:
      routes:
        - id: users-service
          uri: http://${USERS_SERVICE_URL}:8080 # <-- ¡CAMBIO CRUCIAL! Usamos HTTP directo con la variable de entorno y el puerto
          predicates:
            - Path=/api/users/**
          filters:
            - StripPrefix=1

        - id: auth-service
          uri: http://${AUTH_SERVICE_URL}:8080 # <-- ¡CAMBIO CRUCIAL!
          predicates:
            - Path=/api/auth/**
          filters:
            - StripPrefix=1

        - id: prod-service
          uri: http://${PROD_SERVICE_URL}:8080 # <-- ¡CAMBIO CRUCIAL!
          predicates:
            - Path=/api/products/**
          filters:
            - StripPrefix=1

        - id: file-service
          uri: http://${FILE_SERVICE_URL}:8080 # <-- ¡CAMBIO CRUCIAL!
          predicates:
            - Path=/api/files/**
          filters:
            - StripPrefix=1

        - id: order-service
          uri: http://${ORDER_SERVICE_URL}:8080 # <-- ¡CAMBIO CRUCIAL!
          predicates:
            - Path=/api/orders/**
          filters:
            - StripPrefix=1

        - id: stats-service
          uri: http://${STATS_SERVICE_URL}:8080 # <-- ¡CAMBIO CRUCIAL!
          predicates:
            - Path=/api/stats/**
          filters:
            - StripPrefix=1

        - id: health
          uri: http://localhost:8080/actuator/health
          predicates:
            - Path=/health

   