spring:
  config:
    activate:
      on-profile: railway

  cloud:
    gateway:
      routes:
        - id: users-service
          uri: http://users-service.railway.internal:8080
          predicates:
            - Path=/api/users/**
          filters:
            - StripPrefix=1

        - id: auth-service
          uri: http://auth-service.railway.internal:8080
          predicates:
            - Path=/api/auth/**
          filters:
            - StripPrefix=1

        - id: prod-service
          uri: http://prod-service.railway.internal:8080
          predicates:
            - Path=/api/products/**
          filters:
            - StripPrefix=1

        - id: file-service
          uri: http://file-service.railway.internal:8080
          predicates:
            - Path=/api/files/**
          filters:
            - StripPrefix=1

        - id: order-service-deploy
          uri: http://order-service-deploy.railway.internal:8080
          predicates:
            - Path=/api/orders/**
          filters:
            - StripPrefix=1

        - id: stats-service
          uri: http://stats-service.railway.internal:8080
          predicates:
            - Path=/api/stats/**
          filters:
            - StripPrefix=1
