# src/main/resources/application.yml
server:
  port: ${PORT:8080}

spring:
  application:
    name: aec-gateway

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true  
          lower-case-service-id: true

      routes: [] # Deja routes vacío o elimínalo si no tienes rutas comunes.

      globalcors: # Mantener CORS aquí ya que es global y no específico de perfiles de rutas
        corsConfigurations:
          '[/**]':
            allowedOriginPatterns: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
              - PATCH
            allowedHeaders: "*"
            allowCredentials: true
            maxAge: 3600

management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway
  endpoint:
    health:
      show-details: always
    gateway:
      enabled: true

logging:
  level:
    org.springframework.cloud.gateway: TRACE # Cambiamos a TRACE para la depuración
    org.springframework.web.cors: DEBUG
    com.aec.gateway: DEBUG
    org.springframework.cloud.loadbalancer: TRACE # Añadimos TRACE para LoadBalancer
