# application-railway.yml
# Este perfil se activa cuando la aplicación se ejecuta en el entorno de Railway.
spring:
  config:
    activate:
      on-profile: railway # Activa este perfil para Railway

  cloud:
    gateway:
      routes:
        # Ruta para el servicio de usuarios
        - id: users-service
          uri: ${USERS_SERVICE_URL} # <--- ¡Importante! Lee directamente la variable de entorno
          predicates:
            - Path=/api/users/**
          filters:
            - StripPrefix=1

        # Ruta para el servicio de autenticación
        - id: auth-service
          uri: ${AUTH_SERVICE_URL} # <--- ¡Importante! Lee directamente la variable de entorno
          predicates:
            - Path=/api/auth/**
          filters:
            - StripPrefix=1

        # Ruta para el servicio de productos
        - id: prod-service
          uri: ${PROD_SERVICE_URL} # <--- ¡Importante! Lee directamente la variable de entorno
          predicates:
            - Path=/api/products/**
          filters:
            - StripPrefix=1

        # Ruta para el servicio de archivos
        - id: file-service
          uri: ${FILE_SERVICE_URL} # <--- ¡Importante! Lee directamente la variable de entorno
          predicates:
            - Path=/api/files/**
          filters:
            - StripPrefix=1

        # Ruta para el servicio de pedidos
        - id: order-service
          uri: ${ORDER_SERVICE_URL} # <--- ¡Importante! Lee directamente la variable de entorno
          predicates:
            - Path=/api/orders/**
          filters:
            - StripPrefix=1

        # Ruta para el servicio de estadísticas
        - id: stats-service
          uri: ${STATS_SERVICE_URL} # <--- ¡Importante! Lee directamente la variable de entorno
          predicates:
            - Path=/api/stats/**
          filters:
            - StripPrefix=1

      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOriginPatterns: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
              - PATCH
            allowedHeaders: "*"
            allowCredentials: true
            maxAge: 3600

server:
  port: ${PORT:8080}

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    root: INFO