spring:
  config:
    activate:
      on-profile: railway

  cloud:
    gateway:
      routes:
        # Configuración principal para archivos - VERSIÓN CORREGIDA
        - id: file-service
          uri: http://${FILE_SERVICE_URL:file-service.railway.internal}:8084
          predicates:
            - Path=/api/files/**
          filters:
          - RemoveRequestHeader=Authorization
          - RemoveRequestHeader=Cookie
          - RemoveResponseHeader=WWW-Authenticate     # <— quita el desafío Bearer
          - SetResponseHeader=Access-Control-Allow-Origin, *
          - SetResponseHeader=Access-Control-Allow-Methods, GET, OPTIONS
          - SetResponseHeader=Access-Control-Expose-Headers, Content-Disposition
          - DedupeResponseHeader=Access-Control-Allow-Credentials, RETAIN_FIRST

        # Servicios adicionales (configuración original)
        - id: users-service
          uri: http://${USERS_SERVICE_URL:users-service.railway.internal}:8081
          predicates:
            - Path=/api/users/**
          filters:
            - StripPrefix=0

        - id: auth-service  
          uri: http://${AUTH_SERVICE_URL:auth-service.railway.internal}:8082
          predicates:
            - Path=/api/auth/**
          filters:
            - StripPrefix=0
            - RemoveRequestHeader=Cookie

        - id: prod-service
          uri: http://${PROD_SERVICE_URL:prod-service.railway.internal}:8083
          predicates:
            - Path=/api/products/**
          filters:
            - StripPrefix=0

        - id: order-service
          uri: http://${ORDER_SERVICE_URL:order-service-deploy.railway.internal}:8085
          predicates:
            - Path=/api/orders/**
          filters:
            - StripPrefix=0

        - id: stats-service
          uri: http://${STATS_SERVICE_URL:stats-service.railway.internal}:8086
          predicates:
            - Path=/api/stats/**
          filters:
            - StripPrefix=1

        - id: aecf-frontend
          uri: http://aecf.railway.internal:80
          predicates:
            - Path=/, /index.html, /static/**, /*.js, /*.css, /*.json, /*.png
          filters:
            - SetResponseHeader=Cache-Control, no-cache

      discovery:
        locator:
          enabled: false
      httpclient:
        connect-timeout: 10000
        response-timeout: 60s  # Aumentado timeout

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, gateway
      base-path: /management
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true

logging:
  level:
    org.springframework.cloud.gateway: TRACE  # Cambiado a TRACE para más detalle
    org.springframework.web: DEBUG
    reactor.netty: DEBUG
    root: INFO