#
#  Este archivo SOLO se carga cuando el perfil activo es `railway`
#  (SPRING_PROFILES_ACTIVE=railway).  No usa lb://  — se enruta por
#  URL directa (http://…:8080) que Railway resuelve internamente.
#
spring:
  config:
    activate:
      on-profile: railway                     # ← clave

  cloud:
    gateway:
      routes:

        # ────────────── USERS ──────────────
        - id: users-service
          uri: ${USERS_SERVICE_URL}           # http://<uuid>.railway.internal:8080
          predicates:
            - Path=/api/users/**
          filters:
            - StripPrefix=1

        # ────────────── AUTH ──────────────
        - id: auth-service
          uri: ${AUTH_SERVICE_URL}
          predicates:
            - Path=/api/auth/**
          filters:
            - StripPrefix=1

        # ────────────── PRODUCTS ──────────────
        - id: prod-service
          uri: ${PROD_SERVICE_URL}
          predicates:
            - Path=/api/products/**
          filters:
            - StripPrefix=1

        # ────────────── FILES ──────────────
        - id: file-service
          uri: ${FILE_SERVICE_URL}
          predicates:
            - Path=/api/files/**
          filters:
            - StripPrefix=1

        # ────────────── ORDERS ──────────────
        - id: order-service
          uri: ${ORDER_SERVICE_URL}
          predicates:
            - Path=/api/orders/**
          filters:
            - StripPrefix=1

        # ────────────── STATS ──────────────
        - id: stats-service
          uri: ${STATS_SERVICE_URL}
          predicates:
            - Path=/api/stats/**
          filters:
            - StripPrefix=1

        # ────────────── HEALTH LOCAL ──────────────
        - id: health
          uri: http://localhost:8080/actuator/health
          predicates:
            - Path=/health

      #
      #  CORS global.  (Si ya tienes CorsWebFilter en un @Bean,
      #  puedes dejarlo; esto no hace daño.)
      #
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOriginPatterns: '*'
            allowedMethods: [GET, POST, PUT, DELETE, OPTIONS, PATCH]
            allowedHeaders: '*'
            allowCredentials: true
            maxAge: 3600

server:
  port: ${PORT:8080}

logging:
  level:
    org.springframework.cloud.gateway: INFO
    root: INFO
