spring:
  config:
    activate:
      on-profile: railway

  cloud:
    gateway:
      routes:
        - id: users-service
          uri: https://${{users-service.RAILWAY_PRIVATE_DOMAIN}}
          predicates:
            - Path=/api/users/**

        - id: auth-service
          uri: https://${{auth-service.RAILWAY_PRIVATE_DOMAIN}}
          predicates:
            - Path=/api/auth/**

        - id: prod-service
          uri: https://${{prod-service.RAILWAY_PRIVATE_DOMAIN}}
          predicates:
            - Path=/api/products/**

        - id: file-service
          uri: https://${{file-service.RAILWAY_PRIVATE_DOMAIN}}
          predicates:
            - Path=/api/files/**

        - id: order-service-deploy
          uri: https://${{order-service-deploy.RAILWAY_PRIVATE_DOMAIN}}
          predicates:
            - Path=/api/orders/**

        - id: stats-service
          uri: https://${{stats-service.RAILWAY_PRIVATE_DOMAIN}}
          predicates:
            - Path=/api/stats/**