spring:
  config:
    activate:
      on-profile: railway

  cloud:
    gateway:
      routes:
        - id: users-service
          uri: ${USERS_SERVICE_URL}
          predicates:
            - Path=/api/users/**
          filters:
            - StripPrefix=1

        - id: auth-service
          uri: ${AUTH_SERVICE_URL}
          predicates:
            - Path=/api/auth/**
          filters:
            - StripPrefix=1

        - id: prod-service
          uri: ${PROD_SERVICE_URL}
          predicates:
            - Path=/api/products/**
          filters:
            - StripPrefix=1

        - id: file-service
          uri: ${FILE_SERVICE_URL}
          predicates:
            - Path=/api/files/**
          filters:
            - StripPrefix=1

        - id: order-service
          uri: ${ORDER_SERVICE_URL}
          predicates:
            - Path=/api/orders/**
          filters:
            - StripPrefix=1

        - id: stats-service
          uri: ${STATS_SERVICE_URL}
          predicates:
            - Path=/api/stats/**
          filters:
            - StripPrefix=1

      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOriginPatterns: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
              - PATCH
            allowedHeaders: "*"
            allowCredentials: true
            maxAge: 3600

server:
  port: ${PORT:8080}

logging:
  level:
    org.springframework.cloud.gateway: INFO
    root: INFO
