spring:
  config:
    activate:
      on-profile: railway

  cloud:
    gateway:
      routes:
        - id: users-service-railway
          uri: http://users-service:8080
          predicates:
            - Path=/api/users/**
          filters:
            - StripPrefix=1

        - id: auth-service-railway
          uri: http://auth-service:8080
          predicates:
            - Path=/api/auth/**
          filters:
            - StripPrefix=1

        - id: prod-service-railway
          uri: http://prod-service:8080
          predicates:
            - Path=/api/products/**
          filters:
            - StripPrefix=1

        - id: file-service-railway
          uri: http://file-service:8080
          predicates:
            - Path=/api/files/**
          filters:
            - StripPrefix=1

        - id: order-service-railway
          uri: http://order-service-deploy:8080
          predicates:
            - Path=/api/orders/**
          filters:
            - StripPrefix=1

        - id: stats-service-railway
          uri: http://stats-service:8080
          predicates:
            - Path=/api/stats/**
          filters:
            - StripPrefix=1

      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOriginPatterns:
              - "https://aecf.railway.internal"
              - "https://*.railway.app"
              - "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
              - PATCH
            allowedHeaders: "*"
            allowCredentials: true
            maxAge: 3600

server:
  port: ${PORT:8080}

logging:
  level:
    org.springframework.cloud.gateway: INFO
    root: INFO
