server:
  port: ${PORT:8080}

spring:
  application:
    name: aec-gateway

  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOriginPatterns: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
              - PATCH
            allowedHeaders: "*"
            allowCredentials: true
            maxAge: 3600

      routes:
        - id: users-service-local
          uri: http://localhost:8081
          predicates:
            - Path=/api/users/**
          metadata:
            profile: local

        - id: auth-service-local
          uri: http://localhost:8082
          predicates:
            - Path=/api/auth/**
          metadata:
            profile: local

        - id: prod-service-local
          uri: http://localhost:8083
          predicates:
            - Path=/api/products/**
          metadata:
            profile: local

        - id: file-service-local
          uri: http://localhost:8084
          predicates:
            - Path=/api/files/**
          metadata:
            profile: local

        - id: order-service-local
          uri: http://localhost:8085
          predicates:
            - Path=/api/orders/**
          metadata:
            profile: local

        - id: stats-service-local
          uri: http://localhost:8086
          predicates:
            - Path=/api/stats/**
          metadata:
            profile: local

management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway
  endpoint:
    health:
      show-details: always
    gateway:
      enabled: true

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.web.cors: DEBUG
    com.aec.gateway: DEBUG
    root: INFO