server:
  port: ${PORT:8081}

spring:
  application:
    name: gateway
  
  cloud:
    gateway:
      routes:
        # Ruta para Users Service
        - id: users-service
          uri: http://users-service.railway.internal
          predicates:
            - Path=/api/users/**
          filters:
            - StripPrefix=1
        
        # Ruta para Auth Service
        - id: auth-service
          uri: http://auth-service.railway.internal
          predicates:
            - Path=/api/auth/**
          filters:
            - StripPrefix=1
        
        # Ruta para Products Service
        - id: prod-service
          uri: http://prod-service-deploy.railway.internal
          predicates:
            - Path=/api/products/**
          filters:
            - StripPrefix=1
        
        # Ruta para Files Service
        - id: file-service
          uri: http://file-service.railway.internal
          predicates:
            - Path=/api/files/**
          filters:
            - StripPrefix=1
        
        # Ruta para Orders Service
        - id: order-service-deploy
          uri: http://order-service-deploy.railway.internal
          predicates:
            - Path=/api/orders/**
          filters:
            - StripPrefix=1
        
        # Ruta para Stats Service
        - id: stats-service
          uri: http://stats-service.railway.internal
          predicates:
            - Path=/api/stats/**
          filters:
            - StripPrefix=1

      # Configuración global de CORS
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - PATCH
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: false

# Configuración de logging
logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty: INFO
    org.springframework.web: DEBUG

# Configuración de management endpoints
management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway
  endpoint:
    health:
      show-details: always