spring:
  config:
    activate:
      on-profile: railway

  cloud:
    gateway:
      routes:
        - id: file-service-products
          uri: http://${FILE_SERVICE_URL:file-service.railway.internal}:8084
          predicates:
            - Path=/api/files/products/{id}/{filename} 
          filters:
            - RewritePath=/api/files/products/(?<id>\d+)/(?<filename>.*), /api/files/${id}/${filename}
            - StripPrefix=0

        - id: file-service-receipts
          uri: http://${FILE_SERVICE_URL:file-service.railway.internal}:8084
          predicates:
            - Path=/api/files/receipts/{id}/{filename} 
          filters:
            - RewritePath=/api/files/receipts/(?<id>\d+)/(?<filename>.*), /api/files/${id}/${filename}
            - StripPrefix=0

        - id: file-service-generic
          uri: http://${FILE_SERVICE_URL:file-service.railway.internal}:8084
          predicates:
            - Path=/api/files/{id}/{filename} 
          filters:
            - StripPrefix=1  

        - id: users-service
          uri: http://${USERS_SERVICE_URL:users-service.railway.internal}:8081
          predicates:
            - Path=/api/users/**
          filters:
            - StripPrefix=0

        - id: auth-service  
          uri: http://${AUTH_SERVICE_URL:auth-service.railway.internal}:8082
          predicates:
            - Path=/api/auth/**
          filters:
            - StripPrefix=0
            - RemoveRequestHeader=Cookie 
            - name: RewritePath
              args:
                regexp: /api/auth/(?<segment>.*)
                replacement: /api/auth/$\{segment}

        - id: prod-service
          uri: http://${PROD_SERVICE_URL:prod-service.railway.internal}:8083
          predicates:
            - Path=/api/products/**
          filters:
            - StripPrefix=0

        - id: order-service
          uri: http://${ORDER_SERVICE_URL:order-service-deploy.railway.internal}:8085
          predicates:
            - Path=/api/orders/**
          filters:
            - StripPrefix=0

        - id: stats-service
          uri: http://${STATS_SERVICE_URL:stats-service.railway.internal}:8086
          predicates:
            - Path=/api/stats/**
          filters:
            - StripPrefix=0

        - id: aecf
          uri: http://aecf.railway.internal:80
          predicates:
            - Path=/, /index.html, /static/**, /*.js, /*.css, /*.json, /*.png

      discovery:
        locator:
          enabled: false

management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway
  endpoint:
    health:
      show-details: always

logging:
  level:
    org.springframework.cloud.gateway: TRACE
    org.springframework.web.cors: DEBUG
    com.aec.gateway: INFO
    root: INFO
