
spring:
  config:
    activate:
      on-profile: railway

  cloud:
    gateway:
      routes:
        - id: users-service
          uri: http://${USERS_SERVICE_URL}
          predicates:
            - Path=/api/users/**

        - id: auth-service
          uri: http://${AUTH_SERVICE_URL}
          predicates:
            - Path=/api/auth/**

        - id: prod-service
          uri: http://${PROD_SERVICE_URL}
          predicates:
            - Path=/api/products/**

        - id: file-service
          uri: http://${FILE_SERVICE_URL}
          predicates:
            - Path=/api/files/**

        - id: order-service
          uri: http://${ORDER_SERVICE_URL}
          predicates:
            - Path=/api/orders/**

        - id: stats-service
          uri: http://${STATS_SERVICE_URL}
          predicates:
            - Path=/api/stats/**